LearningRails/steam/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "games" => "games#show", as: :games
  get "core" => "games#testeDeGame", as: :coreKepper

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

LearningRails/steam/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

LearningRails/steam/app/models/game.rb
require "active_record"


class Game<ActiveRecord::Base
end

LearningRails/steam/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

LearningRails/steam/app/controllers/games_controller.rb
class GamesController <ActionController::Base
  def show
    @nome = "Teste deu bom"
    render "index"
  end
  def testeDeGame
    @nomeDoGame = "Core Keeper"
    @preco = 75.10
    @studio = "FrontPage"
    render "coreKepper"
  end

  def nome
    @nomeDoGame = Game.find[params[:name]]
    render "coreKepper"
  end
end

LearningRails/steam/app/helpers/application_helper.rb
module ApplicationHelper
end

LearningRails/steam/app/views/games/coreKepper.html.erb
<h1> Aqui jaz o meu codigo tentando criar uma view para o método de instancia </h1>
<h2> games#testeDeGame</h2>

<ul>
  <li> Nome do game é <%= @nomeDoGame%>
  </li>

  <li> O preco do game é <%= @preco%>
  </li>

  <li> O estudio que fez o game é  <%= @studio%>
  </li>

</ul>

<%= link_to "Ir para a primeira pagina", games_path %>
<%= link_to "Ir para a pagina up", rails_health_check_path %>

LearningRails/steam/app/views/games/index.html.erb
<h1>Opa chegamos aqui</h1>
<p>

<%= @nome %>

</p>

LearningRails/steam/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Steam" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>